/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import modelDominio.Comunidade;

/**
 *
 * @author aluno
 */
public class TelaMenuTags extends javax.swing.JFrame {

    private Comunidade comunidade;

    public TelaMenuTags(Comunidade c) {
        this.comunidade = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jbtnVoltar = new javax.swing.JButton();
        jbtnTagsDeMusica = new javax.swing.JButton();
        jbtnTagsComunidade = new javax.swing.JButton();
        jbtnTagsDeAlbum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logoRoxoComNomeMaisPequena.png"))); // NOI18N

        jbtnVoltar.setBackground(new java.awt.Color(80, 0, 198));
        jbtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnVoltar.setText("Home");
        jbtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVoltarActionPerformed(evt);
            }
        });

        jbtnTagsDeMusica.setBackground(new java.awt.Color(80, 0, 198));
        jbtnTagsDeMusica.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTagsDeMusica.setText("Tags de Música");
        jbtnTagsDeMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTagsDeMusicaActionPerformed(evt);
            }
        });

        jbtnTagsComunidade.setBackground(new java.awt.Color(80, 0, 198));
        jbtnTagsComunidade.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTagsComunidade.setText("Tags da Comunidade");
        jbtnTagsComunidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTagsComunidadeActionPerformed(evt);
            }
        });

        jbtnTagsDeAlbum.setBackground(new java.awt.Color(80, 0, 198));
        jbtnTagsDeAlbum.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTagsDeAlbum.setText("Tags de Álbum");
        jbtnTagsDeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTagsDeAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(373, 373, 373))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 321, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTagsDeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTagsComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTagsDeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(316, 316, 316))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnVoltar)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(88, 88, 88)
                .addComponent(jbtnTagsComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnTagsDeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnTagsDeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVoltarActionPerformed
        TelaComunidade tc = new TelaComunidade(comunidade);
        tc.setLocationRelativeTo(null);
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnVoltarActionPerformed

    private void jbtnTagsDeMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTagsDeMusicaActionPerformed
        //0 = tags adicionadas;  2 = lista de musicas; 7 = lista de albuns
        TelaGerenciamentoTags tgt = new TelaGerenciamentoTags(comunidade, 2);
        tgt.setLocationRelativeTo(null);
        tgt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnTagsDeMusicaActionPerformed

    private void jbtnTagsComunidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTagsComunidadeActionPerformed
        //0 = tags adicionadas;  2 = lista de musicas; 7 = lista de albuns
        TelaGerenciamentoTags tgt = new TelaGerenciamentoTags(comunidade, 0);
        tgt.setLocationRelativeTo(null);
        tgt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnTagsComunidadeActionPerformed

    private void jbtnTagsDeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTagsDeAlbumActionPerformed
        //0 = tags adicionadas;  2 = lista de musicas; 7 = lista de albuns
        TelaGerenciamentoTags  tgt = new TelaGerenciamentoTags(comunidade, 7);
        tgt.setLocationRelativeTo(null);
        tgt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnTagsDeAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuTags(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnTagsComunidade;
    private javax.swing.JButton jbtnTagsDeAlbum;
    private javax.swing.JButton jbtnTagsDeMusica;
    private javax.swing.JButton jbtnVoltar;
    // End of variables declaration//GEN-END:variables
}
